### PR TITLE
Add nodejs and cbindgen dependency for building Firefox.

### PR DESCRIPTION
**Pull request by nbp**
This pull request adds nodejs and cbindgen dependencies to gecko dev environment.

Unfortunately, nixos-18.03 does not have `nodejs-8_x` as the default, and not does include `rust-cbindgen` yet, as opposed to nixos-unstable. Therefore, this commit does a bit of work-around to work on top of nixos-18.03 by importing them from Nixpkgs, or comparing the versions to check if we have the desired version or not.

### CODE REVIEW

**Comment by johnae** [comment]
I'm on nixos unstable and I now get this error:

```
error: attempt to call something which is not a function but a set, at /nix/store/kcdh3m23dy3vxzlrwj3kwjg02616kgbd-source/firefox-overlay.nix:172:19
```

It seems it's trying to call the rust-cbindgen that comes with nixpkgs but that is not a function.
